# Generated by Django 3.2.25 on 2024-08-03 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_voetbalspeler_auteur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voetbalspeler',
            old_name='auteur',
            new_name='author',
        ),
    ]
