# Generated by Django 3.2.25 on 2024-08-03 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_auteur_voetbalspeler_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voetbalspeler',
        ),
    ]
